### ISSUE TITLE
Bug: The plugin cannot be logged in, which conflicts with the proxy setting parameters of the IDE.

### ISSUE THREAD

**Issue by hhstore** [Exafunction/CodeiumJetBrains#30]
## Bug:

- When clicking on the login button, there is no `pop-up login page`, no response, and no obvious error.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/2123d19c-19e6-4259-a9ea-c33bb9a40ffa">

## IDE Plugin Crash Logs:

- https://github.com/Codium-ai/codiumai-jetbrains-release/issues/245#issuecomment-2228915471

```ruby

Unhandled exception in [StandaloneCoroutine{Cancelling}@3340a3b, Dispatchers.IO]

com.intellij.execution.IllegalEnvVarException: Illegal value of environment variable value 'NO_PROXY': 'null'
	at com.intellij.execution.configurations.GeneralCommandLine.validateAndPrepareCommandLineForLocalRun(GeneralCommandLine.java:420)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:350)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.codeium.intellij.language_server.LanguageServerProcessHandler.<init>(LanguageServerProcessHandler.kt:18)
	at com.codeium.intellij.language_server.LanguageServerLauncherActivity$runActivity$1.invokeSuspend(LanguageServerLauncherActivity.kt:394)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@3340a3b, Dispatchers.IO]

```

<img width="600" alt="image" src="https://github.com/user-attachments/assets/271a9699-6839-4f33-b09c-4c4d9e305358">

- This error refers to the `proxy setting` in the `IDE settings`, not the global `environment variables`. 

## Temporary Solution: 

- ✅ It conflicts with the IDE's `proxy settings`, you need to check `no proxy`, you can't set `proxy`. 
- ✅ Select `no proxy`, and you can `log in` normally.  
- ✅ This should be a `bug`, setting `proxy` to some users, is required.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/15791e7d-73ca-46b8-8f60-ed5eff25e96b">

**Comment by fortenforge** [comment]
This is fixed on the latest release; just update
