### ISSUE TITLE
`Invalid URL port: "0"`: Codeium not working

### ISSUE THREAD

**Issue by cesarizu** [Exafunction/CodeiumJetBrains#34]
Codeium is not working anymore for me. I see this exception:

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@4f4345f7, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@78692e1a, Dispatchers.IO]
```

**Comment by daiwuxing** [comment]
I ran into the same problem

**Comment by Algomorph** [comment]
A am also not able to login w/ ~same~ similar error.
Error 1:
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@51a08644, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@51a08644, Dispatchers.IO]
```
Error 2:
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@c6d9f05, Dispatchers.IO]

com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/home/greg/.local/share/JetBrains/CLion2024.1/codeium/4afed79fc3218d4ed6a74b3082a291b8e866ba19/language_server_linux_x64": error=26, Text file busy
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:367)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.codeium.intellij.language_server.LanguageServerProcessHandler.<init>(LanguageServerProcessHandler.kt:18)
	at com.codeium.intellij.language_server.LanguageServerLauncherActivity$executeLanguageServer$1.invokeSuspend(LanguageServerLauncherActivity.kt:466)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@c6d9f05, Dispatchers.IO]
Caused by: java.io.IOException: Cannot run program "/home/greg/.local/share/JetBrains/CLion2024.1/codeium/4afed79fc3218d4ed6a74b3082a291b8e866ba19/language_server_linux_x64": error=26, Text file busy
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:491)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:464)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:357)
	... 13 more
Caused by: java.io.IOException: error=26, Text file busy
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 17 more
```
Error 3:
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@68912a74, Dispatchers.IO]

java.nio.file.NoSuchFileException: /home/greg/.local/share/JetBrains/CLion2024.1/codeium/4afed79fc3218d4ed6a74b3082a291b8e866ba19/language_server_linux_x64.download -> /home/greg/.local/share/JetBrains/CLion2024.1/codeium/4afed79fc3218d4ed6a74b3082a291b8e866ba19/language_server_linux_x64
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at com.codeium.intellij.language_server.LanguageServerLauncherActivity$runActivity$1$3$1.invokeSuspend(LanguageServerLauncherActivity.kt:323)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@68912a74, Dispatchers.IO]
```

System / IDE/ Codeium version:
```
CLion 2024.1.5
Build #CL-241.19072.20, built on August 9, 2024
Licensed to Presage Security, Inc / Gregory Kramida
Subscription is active until November 19, 2024.
Runtime version: 17.0.11+1-b1207.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-45-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  terminal.new.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (241.15989.49)
  com.codeium.intellij (1.10.11)
  com.mikejhill.intellij.movetab (2.1.1)
  com.google.idea.bazel.clwb (2024.07.16.0.1-api-version-241)
Current Desktop: ubuntu:GNOME
```

https://github.com/Exafunction/CodeiumJetBrains/issues/13#issuecomment-2284930425
https://github.com/Exafunction/codeium/issues/76
https://github.com/Exafunction/codeium.vim/issues/425

**Comment by BartZuc** [comment]
Plugin and chat is working (i don't see problem) except of stacktrace in IDE Errors.

IDE: `JetBrains Rider 2024.1.5`
Plugin: `Codeium AI 1.10.11`
System: `Windows 10 Pro 22H2`

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@63b95bae, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@63b95bae, Dispatchers.IO]
```

**Comment by SwathingSoap** [comment]
+

**Comment by avpaderno** [comment]
Like @BartZuc, I noticed the plugin works, despite the thrown exception.  
I still see *Codeium: Refactor*, *Explain*, and *Docstring*. When I click on them, the plugin works as usual.

**Comment by cesarizu** [comment]
For me it just doesn't work at all. It was working normally before. When I try to log in it pops up this window but nothing happens:

![Screenshot 2024-08-14 105843](https://github.com/user-attachments/assets/8c55e52a-0405-49c5-9039-b2397118c967)

Furthermore I see this on the logs:

```
2024-08-12 21:58:42,527 [48440594]   WARN - #com.codeium.intellij.language_server.LanguageServerService - Unable to get process ports...language server not started
2024-08-12 21:58:42,529 [48440596]   INFO - #com.codeium.intellij.chat_window.ChatViewerWindow - Refreshed process ports: 
2024-08-12 21:58:42,536 [48440603] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in [StandaloneCoroutine{Cancelling}@4f4345f7, Dispatchers.IO]
java.lang.IllegalArgumentException: Invalid URL port: "0"
```

And in a different part:

```
2024-08-12 21:58:58,201 [48456268]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: I0812 21:58:58.201276 21380 main.go:288] Failed to get random ports within 15 seconds
2024-08-12 21:59:01,496 [48459563]   INFO - #c.i.o.a.i.ActionPopupMenuImpl - isPopupOrMainMenuPlace(NotificationManager)==false. Use ActionPlaces.getPopupPlace.
2024-08-12 21:59:02,527 [48460594]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: E0812 21:59:02.523566 21380 cmd_wrapper.go:265] LanguageServer wait failed: timed out while waiting on process 23172 at 0812 21:59:02.519026, sent SIGTERM then SIGKILL
2024-08-12 21:59:02,528 [48460595]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: E0812 21:59:02.528566 21380 main.go:240] Failed to remove stderr file C:\Users\CESARA~1\AppData\Local\Temp\18290950436365280420\codeium\manager/server_outputs/language_server_stderr_1723514323134259600_7936393574512133583: remove C:\Users\CESARA~1\AppData\Local\Temp\18290950436365280420\codeium\manager/server_outputs/language_server_stderr_1723514323134259600_7936393574512133583: The process cannot access the file because it is being used by another process.
```

**Comment by Algomorph** [comment]
Same `Invalid URL port: "0"` error occurring for me in CLion 2024.2. Still unable to log in.
Attaching log.

[idea.log](https://github.com/user-attachments/files/16615593/idea.log)

**Comment by Orangeym** [comment]
I'm in the same boat, how should this problem be solved
Unhandled exception in [StandaloneCoroutine{Cancelling}@6614a24e, Dispatchers.IO]
  
  java.lang.IllegalArgumentException: Invalid URL port: "0"
at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
at okhttp3.Request$Builder.url(Request.kt:184)
at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6614a24e, Dispatchers.IO]

**Comment by avpaderno** [comment]
I was logged in before the error started to appear and I am still logged in. Maybe that is the difference.

I recall a similar error already happened in the past. The cause was different, but the effect was the same.

**Comment by st4s1k** [comment]
Works on another laptop with RustRover, doesn't work on my personal laptop with RustRover (doesn't work for *.rs files, but works for JSON), that is just weird. The IDEs and the plugin are all up to date.

```java
Unhandled exception in [StandaloneCoroutine{Cancelling}@956150a, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@956150a, Dispatchers.IO]

```

**Comment by noembryo** [comment]
Same here..
Codeium 1.10.11
Intellij IDEA 2023.3.1
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@438749b, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@438749b, Dispatchers.IO]
```

**Comment by Algomorph** [comment]
I was able to log in again with version `1.12.6`!
Steps:
1. Upgrade to Codeium JetBrains Plugin 1.12.6, disable the plugin, and close the IDE
2. Delete the `.codeium` folder in your $HOME folder
3. Start IDE, re-enable plugin, restart IDE as required.
4. Log in afresh.

**Comment by noembryo** [comment]
Yes, my errors are also disappeared after installing 1.12.6.. 👍 🥳

**Comment by Algomorph** [comment]
Observation: updated to `1.12.6` on Mac _and_ the JetBrains IDE to latest version and _then_ bug came out, but the plugin kept on working. I think that maybe the bug is still around and does depend on some outdated stuff in the `.codeium` folder. Somehow, it isn't a showstopper on MacOS but is on Linux.

**Comment by avpaderno** [comment]
The past week I saw some unhandled exceptions for some plugins, not only the Codeium plugin, but also the *OpenAPI Specifications* plugin (which is a bundled plugin).

I am using PhpStorm 2024.2.0.1 (Build #PS-242.20224.427, built on August 21, 2024) and the Codeium plugin 1.14.9.

**Comment by alexsvt2** [comment]
> I was able to log in again with version `1.12.6`! Steps:
> 
> 1. Upgrade to Codeium JetBrains Plugin 1.12.6, disable the plugin, and close the IDE
> 2. Delete the `.codeium` folder in your $HOME folder
> 3. Start IDE, re-enable plugin, restart IDE as required.
> 4. Log in afresh.

This worked well for me, thank you.

I was facing the same error with WebStorm 2024.2.3 and Codeium 1.20.4 and I removed the folder of codeium in 
C:\Users\userName\\.codeium

**Comment by ggfickle** [comment]
> I was able to log in again with version `1.12.6`! Steps:
> 
> 1. Upgrade to Codeium JetBrains Plugin 1.12.6, disable the plugin, and close the IDE
> 2. Delete the `.codeium` folder in your $HOME folder
> 3. Start IDE, re-enable plugin, restart IDE as required.
> 4. Log in afresh.

it's worked! I must say an old Chinese saying to praise you, Niubi!

**Comment by qingpengchen2011** [comment]
> > I was able to log in again with version `1.12.6`! Steps:
> > 
> > 1. Upgrade to Codeium JetBrains Plugin 1.12.6, disable the plugin, and close the IDE
> > 2. Delete the `.codeium` folder in your $HOME folder
> > 3. Start IDE, re-enable plugin, restart IDE as required.
> > 4. Log in afresh.
> 
> it's worked! I must say an old Chinese saying to praise you, Niubi!

it works bro.
