### ISSUE TITLE
Codeium chat blank

### ISSUE THREAD

**Issue by githubmo** [Exafunction/CodeiumJetBrains#39]
IntelliJ 2024.2.1
Codeium plugin 1.16.4
Fedora 40

I cannot get Codeium chat to work on IntelliJ in Linux. Works fine on my Mac. Also Pycharm Professional on Linux works with Codeium. It seems in the Idea logs I get errors trying to connect to the chat server.

![image](https://github.com/user-attachments/assets/779b4dc4-0236-41b3-8a67-d6f96e12c262)

```
2024-09-17 08:36:15,706 [  17350]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: W0917 08:36:15.706765 483341 main.go:124] LS MANAGER: Language server manager got signal interrupt, shutting down
2024-09-17 08:36:15,706 [  17350]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: W0917 08:36:15.706765 483368 server.go:345] Got signal interrupt, shutting down
2024-09-17 08:36:15,706 [  17350]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: I0917 08:36:15.706811 483368 server.go:768] Language server shutting down
2024-09-17 08:36:15,707 [  17351]   WARN - #com.codeium.intellij.language_server.LanguageServerService - Error refreshing context
io.grpc.StatusException: UNAVAILABLE: Channel shutdownNow invoked
	at io.grpc.Status.asException(Status.java:548)
	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:300)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-17 08:36:15,722 [  17366]   INFO - #o.j.i.BuiltInServer - web server stopped
2024-09-17 08:36:15,722 [  17366]   WARN - #com.codeium.intellij.chat_server_client.ChatServerClient - [ChatServerClient] WebSocket connection failed with error: java.io.EOFException
2024-09-17 08:36:15,723 [  17367]   INFO - #o.j.p.s.c.CompileServerLauncher$ - Shutdown event triggered, stopping server
2024-09-17 08:36:15,723 [  17367]   INFO - #o.j.p.s.c.CompileServerLauncher$ - compile server process stop: pid: 483563, port: 3200, jdk: JDK(/home/mo/.sdkman/candidates/java/17.0.12-tem/bin/java,None,temurin-17 (3),Some(JDK_17)), jvmParameters: -server,-Xss2m,-XX:MaxInlineLevel=20,-Xmx2048m,-XX:+UseParallelGC, jpsUseUnifiedIC: false, stopped: false, running: true, errors: 
2024-09-17 08:36:15,727 [  17371]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - [Language Server]: I0917 08:36:15.727156 483341 cmd_wrapper.go:267] LS MANAGER: LanguageServer exited with: success
2024-09-17 08:36:15,731 [  17375]   INFO - #com.codeium.intellij.language_server.LanguageServerProcessHandler - Language server terminated
```

![image](https://github.com/user-attachments/assets/f66fc627-8d9c-4d97-bf61-738aa1183653)

**Comment by BlackArbsCEO** [comment]
I have this same issue. codeium works fine with vscode but not pycharm on fedora kinoite

**Comment by kas-cor** [comment]
Install the regular version and the jre version, it worked for me in Manjaro Linux
