### ISSUE TITLE
Plugin crashes if emoji is used in string

### ISSUE THREAD

**Issue by fortenforge** [Exafunction/CodeiumJetBrains#4]
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@758c7d1c, Dispatchers.IO]

java.lang.IllegalArgumentException: Unpaired surrogate at index 348
    at com.google.common.base.Utf8.encodedLengthGeneral(Utf8.java:94)
    at com.google.common.base.Utf8.encodedLength(Utf8.java:68)
    at codeium.bc.a(SourceFile:165)
    at codeium.at$c.invokeSuspend(SourceFile:153)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@758c7d1c, Dispatchers.IO]
    ```

**Comment by romanstingler** [comment]
can you give an example? 
i tried a string with emoji in PHP works as expected Codeium 1.6.27
![image](https://github.com/Exafunction/CodeiumJetBrains/assets/5576250/a2d60498-c5a5-45ff-8849-e2910b4148b6)

**Comment by fortenforge** [comment]
Unfortunately I have not been able to reproduce this myself
